### ISSUE TITLE
Error running fabric8 in docker

### ISSUE THREAD

**Issue by theresiasnow** [fabric8io/fabric8-docker#11]
Seems like the owner of /home/fabric8/fabric8-karaf is wrong.

``` bash
docker run -P -it fabric8/fabric8 /home/fabric8/fabric8-karaf/bin/fabric8
Unable to update instance pid: Unable to create directory /home/fabric8/fabric8-karaf/instances
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.apache.karaf.main.Main.doLock(Main.java:1442)
    at org.apache.karaf.main.Main.lock(Main.java:1430)
    at org.apache.karaf.main.Main$1.run(Main.java:357)
Caused by: java.lang.RuntimeException: Karaf can't startup, make sure the log file can be accessed and written by the user starting Karaf : java.io.FileNotFoundException: /home/fabric8/fabric8-karaf/lock (Permission denied)
    at org.apache.karaf.main.SimpleFileLock.<init>(SimpleFileLock.java:53)
    ... 7 more
```

**Comment by jstrachan** [comment]
hmm - that last attempted fix didn't fix it :(

**Comment by theresiasnow** [comment]
Docker can be a pain sometimes :-(. Tried applying chown by building my own docker build, got errors too

**Comment by jstrachan** [comment]
:) my local build is working fine - all permissions look good. Hopefully the next docker hub build will work.... 
/me crosses his fingers

**Comment by theresiasnow** [comment]
building from fabric8-docker source now

**Comment by christian-posta** [comment]
just tried with latest dockerfile, seems to work on my end :)

On Fri, Sep 5, 2014 at 6:29 AM, Sigmund Lundgren notifications@github.com
wrote:

> building from fabric8-docker source now
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fabric8io/fabric8-docker/issues/11#issuecomment-54624598
> .

## 

_Christian Posta_
http://www.christianposta.com/blog
http://fabric8.io
twitter: @christianposta

**Comment by theresiasnow** [comment]
Did a pull and rebuilt from source. Works now. Nice and quick job, thanks

**Comment by jstrachan** [comment]
yeah - seems to be an issue with the trusted build though; the chown / chgrp commands don't seem to have any effect

**Comment by christian-posta** [comment]
how to builds migrate from the git repo to the docker repo? and how frequently?

**Comment by theresiasnow** [comment]
That should be it, new image and build -> docker-hub

**Comment by jstrachan** [comment]
@christian-posta usually when you push to the repo it auto-rebuilds it (thats what trusted builds are); but I've pulled the latest version and the fix doesn't seem to be in there.

I wonder if there's some bug in the disk delta-ing (i.e. its reusing its cache?); or some caching issue? Hopefully next time the image changes actual disk image other than permissions it might get fixed...

Unless chown/chgrp has some issue when building on the trusted build?

**Comment by jimmidyson** [comment]
@jstrachan just pulled latest & works fine for me under docker 1.2:

```
fabric8@142a16ad9ede:/opt/fabric8$ find -L /opt/fabric8 ! -user fabric8 -print                                                                                                                
fabric8@142a16ad9ede:/opt/fabric8$
```

and `docker run -P -it fabric8/fabric8 /home/fabric8/bin/fabric8` works fine for me too.

**Comment by jstrachan** [comment]
FWIW it seems that the bug is related to boot2docker; on linux the image always seems to work.

For some reason boot2docker the chown / chmod doesn't seem to work properly on the /opt/fabric8 /opt/fabric8-karaf-1.2.0.BetaX folders

**Comment by jstrachan** [comment]
I've raised this issue https://github.com/boot2docker/boot2docker/issues/527 as it seems there's some boot2docker bug when using the trusted fabric8/fabric8 build which is fine on linux

**Comment by christian-posta** [comment]
That seems to jive, I tested on Linux and worked fine.

On Monday, September 8, 2014, James Strachan notifications@github.com
wrote:

> I've raised this issue boot2docker/boot2docker#527
> https://github.com/boot2docker/boot2docker/issues/527 as it seems
> there's some boot2docker bug when using the trusted fabric8/fabric8 build
> which is fine on linux
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fabric8io/fabric8-docker/issues/11#issuecomment-54794527
> .

## 

_Christian Posta_
http://www.christianposta.com/blog
http://fabric8.io
twitter: @christianposta

**Comment by jstrachan** [comment]
for now to get things to work on boot2docker I've just disabled running as fabric8 so it works again!
